# Generated by Django 3.2.3 on 2021-06-05 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='ReactionType',
        ),
    ]
