# Generated by Django 3.2.3 on 2021-06-05 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20210605_1050'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('number', models.IntegerField(verbose_name='number')),
                ('description', models.TextField(null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='count')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conference')),
                ('dest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReactionButton.reactiontype')),
            ],
        ),
    ]
